In [105]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [106]:
df= sns.load_dataset("iris")

In [107]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [108]:
df["species"].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [109]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [111]:
df.duplicated().sum()

np.int64(1)

In [112]:
df.shape

(150, 5)

In [113]:
from sklearn.model_selection import train_test_split
X=df.drop("species",axis=1)
y=df["species"]

In [114]:
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [115]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [116]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [117]:
from sklearn.neighbors import KNeighborsClassifier
model_knn=KNeighborsClassifier(n_neighbors=13)

In [118]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [119]:
model_knn.score(X_test,y_test)

1.0

In [120]:
from sklearn.svm import SVC
model_svm=SVC(gamma="auto")
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [121]:
model_svm.score(X_test,y_test)

1.0

In [122]:
from sklearn.model_selection import GridSearchCV
classifier_svm = GridSearchCV(model_svm,{
    "C" : [10,20,30],
    "kernel" :["linear","rbf"]
},cv=5,return_train_score=False)

In [123]:
classifier_svm.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [10, 20, 30], 'kernel': ['linear', 'rbf']})

In [124]:
classifier_svm.cv_results_

{'mean_fit_time': array([0.0041965 , 0.00456285, 0.00481324, 0.00417299, 0.00390663,
        0.00405178]),
 'std_fit_time': array([4.55969274e-04, 5.83436482e-04, 6.79876092e-04, 3.07338709e-04,
        8.61467529e-05, 1.56113718e-04]),
 'mean_score_time': array([0.0030436 , 0.00341001, 0.00326695, 0.00301261, 0.00282664,
        0.00320005]),
 'std_score_time': array([0.00035203, 0.00037332, 0.00035884, 0.00011512, 0.00021732,
        0.0001336 ]),
 'param_C': masked_array(data=[10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'}],
 'split0_test_score': array([1.        , 0.96666667, 1.        , 0.96666667, 1.        ,
        0.96666667]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.9       , 0.96666667, 0.9       , 0.9       , 0.9       ,
        0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.9       ,
        0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.97333333, 0.98      , 0.96666667, 0.96666667, 0.96      ,
        0.96      ]),
 'std_test_score': array([0.03887301, 0.01632993, 0.0421637 , 0.03651484, 0.04898979,
        0.03887301]),
 'rank_test_score': array([2, 1, 4, 3, 5, 5], dtype=int32)}

In [125]:
results = pd.DataFrame(classifier_svm.cv_results_)

In [126]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004197,0.000456,0.003044,0.000352,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,2
1,0.004563,0.000583,0.003410,0.000373,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004813,0.000680,0.003267,0.000359,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,4
3,0.004173,0.000307,0.003013,0.000115,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
4,0.003907,0.000086,0.002827,0.000217,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,5
5,0.004052,0.000156,0.003200,0.000134,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,5

In [127]:
results[["param_C","param_kernel","mean_test_score"]].sort_values(by="mean_test_score",ascending=False)

   param_C param_kernel  mean_test_score
1       10          rbf         0.980000
0       10       linear         0.973333
3       20          rbf         0.966667
2       20       linear         0.966667
4       30       linear         0.960000
5       30          rbf         0.960000

In [128]:
classifier_knn=GridSearchCV(model_knn,{
    "n_neighbors" : [5,7,9,11,13],
    "weights" : ["uniform","distance"],
    "algorithm" : ["auto", "ball_tree", "kd_tree", "brute"]
},cv=5,return_train_score=False)

In [129]:
classifier_knn.fit(X  ,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=13),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [5, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']})

In [130]:
classifier_knn.cv_results_

{'mean_fit_time': array([0.00666418, 0.00374298, 0.0037437 , 0.00393381, 0.00474362,
        0.00617242, 0.00530639, 0.00419412, 0.00421691, 0.00370374,
        0.00355768, 0.00440326, 0.00475721, 0.00405579, 0.00438242,
        0.00354967, 0.00390043, 0.00413485, 0.00379014, 0.00371609,
        0.00345244, 0.0036509 , 0.00356827, 0.00381184, 0.00372496,
        0.00364914, 0.00708375, 0.01878014, 0.01218181, 0.01223831,
        0.00865974, 0.00326104, 0.00336924, 0.00352602, 0.00366707,
        0.00357771, 0.0037241 , 0.00333381, 0.00346866, 0.00355067]),
 'std_fit_time': array([2.91602438e-03, 2.57744286e-04, 1.06639319e-04, 2.79610438e-04,
        1.07797673e-03, 3.22871766e-03, 3.15815239e-03, 1.07983466e-03,
        1.54823588e-03, 2.00845860e-04, 1.77875280e-04, 8.44085880e-04,
        2.90881004e-03, 1.06229795e-04, 1.17589095e-03, 1.21112564e-04,
        2.26530705e-04, 6.84315507e-04, 2.25776478e-04, 2.93983338e-04,
        1.37977065e-04, 3.29266330e-05, 1.32848886e-04, 3.34037958e-04,
        2.40172165e-04, 2.14383812e-04, 4.82172614e-03, 6.62331317e-03,
        2.72904742e-03, 2.93127042e-03, 4.40608148e-03, 4.94023547e-05,
        2.52463441e-04, 3.34271194e-04, 4.99229294e-04, 3.89935609e-04,
        3.61123989e-04, 2.84203867e-04, 1.83107307e-04, 5.97224685e-04]),
 'mean_score_time': array([0.00818672, 0.00503278, 0.00622792, 0.00413356, 0.00531759,
        0.00760021, 0.00575881, 0.00479898, 0.00672016, 0.00434551,
        0.0053792 , 0.00479145, 0.01019902, 0.00423722, 0.00599813,
        0.00388265, 0.00562854, 0.00408635, 0.00558553, 0.00427752,
        0.00507994, 0.00395141, 0.00570626, 0.00400953, 0.00529284,
        0.00393724, 0.01364031, 0.01684866, 0.01730714, 0.01257153,
        0.01476479, 0.00358458, 0.00496712, 0.00425611, 0.005865  ,
        0.00397921, 0.00490923, 0.00426431, 0.00522237, 0.00389132]),
 'std_score_time': array([3.72673796e-03, 7.16404580e-04, 1.40613029e-03, 2.04625965e-04,
        1.29961405e-04, 2.45039421e-03, 6.53377256e-04, 1.00476513e-03,
        2.69255300e-03, 7.24552777e-04, 7.69630758e-04, 1.20346905e-03,
        4.44853153e-03, 1.19987560e-04, 9.91773065e-04, 2.52047615e-04,
        8.74776701e-04, 2.81607753e-04, 9.09298080e-05, 4.00903330e-04,
        6.50809224e-04, 6.69335013e-05, 1.59218137e-03, 1.57876484e-04,
        4.93333830e-04, 2.64493581e-04, 1.08982459e-02, 6.92781612e-03,
        5.77471642e-03, 4.70198893e-03, 6.49281533e-03, 1.89487035e-04,
        3.73319998e-04, 7.71656243e-04, 9.37240891e-04, 3.72715244e-04,
        1.43472163e-04, 6.28066971e-04, 6.83782679e-04, 5.07257872e-04]),
 'param_algorithm': masked_array(data=['auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_neighbors': masked_array(data=[5, 5, 7, 7, 9, 9, 11, 11, 13, 13, 5, 5, 7, 7, 9, 9, 11,
                    11, 13, 13, 5, 5, 7, 7, 9, 9, 11, 11, 13, 13, 5, 5, 7,
                    7, 9, 9, 11, 11, 13, 13],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'algorithm': 'auto', 'n_neighbors': 5, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 5, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 7, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 7, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 9, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 9, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 11, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 11, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 13, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 13, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 5, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 5, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 7, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 7, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 9, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 9, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 11, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 11, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 13, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 13, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 5, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 5, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 7, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 7, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 9, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 9, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 11, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 11, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 13, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 13, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 5, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 5, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 7, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 7, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 9, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 9, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 11, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 11, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 13, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 13, 'weights': 'distance'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.93333333, 0.96666667, 0.93333333, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.93333333, 0.96666667, 0.93333333, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.93333333, 0.96666667, 0.93333333, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.93333333, 0.96666667, 0.93333333, 0.96666667]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.93333333, 0.9       , 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 1.        , 1.        , 0.96666667, 0.96666667,
        0.93333333, 0.9       , 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 1.        , 1.        , 0.96666667, 0.96666667,
        0.93333333, 0.9       , 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 1.        , 1.        , 0.96666667, 0.96666667,
        0.93333333, 0.9       , 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 1.        , 1.        , 0.96666667, 0.96666667]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.97333333, 0.96666667, 0.98      , 0.98      , 0.97333333,
        0.97333333, 0.98      , 0.98666667, 0.97333333, 0.98      ,
        0.97333333, 0.96666667, 0.98      , 0.98      , 0.97333333,
        0.97333333, 0.98      , 0.98666667, 0.97333333, 0.98      ,
        0.97333333, 0.96666667, 0.98      , 0.98      , 0.97333333,
        0.97333333, 0.98      , 0.98666667, 0.97333333, 0.98      ,
        0.97333333, 0.96666667, 0.98      , 0.98      , 0.98      ,
        0.97333333, 0.98      , 0.98666667, 0.97333333, 0.98      ]),
 'std_test_score': array([0.02494438, 0.03651484, 0.01632993, 0.01632993, 0.02494438,
        0.02494438, 0.02666667, 0.01632993, 0.02494438, 0.01632993,
        0.02494438, 0.03651484, 0.01632993, 0.01632993, 0.02494438,
        0.02494438, 0.02666667, 0.01632993, 0.02494438, 0.01632993,
        0.02494438, 0.03651484, 0.01632993, 0.01632993, 0.02494438,
        0.02494438, 0.02666667, 0.01632993, 0.02494438, 0.01632993,
        0.02494438, 0.03651484, 0.01632993, 0.01632993, 0.01632993,
        0.02494438, 0.02666667, 0.01632993, 0.02494438, 0.01632993]),
 'rank_test_score': array([22, 37,  5,  5, 22, 22,  5,  1, 22,  5, 22, 37,  5,  5, 22, 22,  5,
         1, 22,  5, 22, 37,  5,  5, 22, 22,  5,  1, 22,  5, 22, 37,  5,  5,
         5, 22,  5,  1, 22,  5], dtype=int32)}

In [131]:
df_knn=pd.DataFrame(classifier_knn.cv_results_)

In [132]:
df_knn

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006664,0.002916,0.008187,0.003727,auto,5,uniform,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,22
1,0.003743,0.000258,0.005033,0.000716,auto,5,distance,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,37
2,0.003744,0.000107,0.006228,0.001406,auto,7,uniform,"{'algorithm': 'auto', 'n_neighbors': 7, 'weigh...",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,5
3,0.003934,0.000280,0.004134,0.000205,auto,7,distance,"{'algorithm': 'auto', 'n_neighbors': 7, 'weigh...",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,5
4,0.004744,0.001078,0.005318,0.000130,auto,9,uniform,"{'algorithm': 'auto', 'n_neighbors': 9, 'weigh...",0.966667,1.0,0.966667,0.933333,1.0,0.973333,0.024944,22
5,0.006172,0.003229,0.007600,0.002450,auto,9,distance,"{'algorithm': 'auto', 'n_neighbors': 9, 'weigh...",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,22
6,0.005306,0.003158,0.005759,0.000653,auto,11,uniform,"{'algorithm': 'auto', 'n_neighbors': 11, 'weig...",0.933333,1.0,1.000000,0.966667,1.0,0.980000,0.026667,5
7,0.004194,0.001080,0.004799,0.001005,auto,11,distance,"{'algorithm': 'auto', 'n_neighbors': 11, 'weig...",0.966667,1.0,1.000000,0.966667,1.0,0.986667,0.016330,1
8,0.004217,0.001548,0.006720,0.002693,auto,13,uniform,"{'algorithm': 'auto', 'n_neighbors': 13, 'weig...",0.933333,1.0,0.966667,0.966667,1.0,0.973333,0.024944,22
9,0.003704,0.000201,0.004346,0.000725,auto,13,distance,"{'algorithm': 'auto', 'n_neighbors': 13, 'weig...",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,5
10,0.003558,0.000178,0.005379,0.000770,ball_tree,5,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 5, '...",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,22
11,0.004403,0.000844,0.004791,0.001203,ball_tree,5,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 5, '...",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,37
12,0.004757,0.002909,0.010199,0.004449,ball_tree,7,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 7, '...",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,5
13,0.004056,0.000106,0.004237,0.000120,ball_tree,7,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 7, '...",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,5
14,0.004382,0.001176,0.005998,0.000992,ball_tree,9,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 9, '...",0.966667,1.0,0.966667,0.933333,1.0,0.973333,0.024944,22
15,0.003550,0.000121,0.003883,0.000252,ball_tree,9,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 9, '...",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,22
16,0.003900,0.000227,0.005629,0.000875,ball_tree,11,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 11, ...",0.933333,1.0,1.000000,0.966667,1.0,0.980000,0.026667,5
17,0.004135,0.000684,0.004086,0.000282,ball_tree,11,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 11, ...",0.966667,1.0,1.000000,0.966667,1.0,0.986667,0.016330,1
18,0.003790,0.000226,0.005586,0.000091,ball_tree,13,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 13, ...",0.933333,1.0,0.966667,0.966667,1.0,0.973333,0.024944,22
19,0.003716,0.000294,0.004278,0.000401,ball_tree,13,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 13, ...",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,5
20,0.003452,0.000138,0.005080,0.000651,kd_tree,5,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 5, 'we...",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,22
21,0.003651,0.000033,0.003951,0.000067,kd_tree,5,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 5, 'we...",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,37
22,0.003568,0.000133,0.005706,0.001592,kd_tree,7,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 7, 'we...",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,5
23,0.003812,0.000334,0.004010,0.000158,kd_tree,7,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 7, 'we...",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,5
24,0.003725,0.000240,0.005293,0.000493,kd_tree,9,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 9, 'we...",0.966667,1.0,0.966667,0.933333,1.0,0.973333,0.024944,22
25,0.003649,0.000214,0.003937,0.000264,kd_tree,9,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 9, 'we...",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,22
26,0.007084,0.004822,0.013640,0.010898,kd_tree,11,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 11, 'w...",0.933333,1.0,1.000000,0.966667,1.0,0.980000,0.026667,5
27,0.018780,0.006623,0.016849,0.006928,kd_tree,11,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 11, 'w...",0.966667,1.0,1.000000,0.966667,1.0,0.986667,0.016330,1
28,0.012182,0.002729,0.017307,0.005775,kd_tree,13,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 13, 'w...",0.933333,1.0,0.966667,0.966667,1.0,0.973333,0.024944,22
29,0.012238,0.002931,0.012572,0.004702,kd_tree,13,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 13, 'w...",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,5
30,0.008660,0.004406,0.014765,0.006493,brute,5,uniform,"{'algorithm': 'brute', 'n_neighbors': 5, 'weig...",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,22
31,0.003261,0.000049,0.003585,0.000189,brute,5,distance,"{'algorithm': 'brute', 'n_neighbors': 5, 'weig...",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,37
32,0.003369,0.000252,0.004967,0.000373,brute,7,uniform,"{'algorithm': 'brute', 'n_neighbors': 7, 'weig...",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,5
33,0.003526,0.000334,0.004256,0.000772,brute,7,distance,"{'algorithm': 'brute', 'n_neighbors': 7, 'weig...",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,5
34,0.003667,0.000499,0.005865,0.000937,brute,9,uniform,"{'algorithm': 'brute', 'n_neighbors': 9, 'weig...",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,5
35,0.003578,0.000390,0.003979,0.000373,brute,9,distance,"{'algorithm': 'brute', 'n_neighbors': 9, 'weig...",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,22
36,0.003724,0.000361,0.004909,0.000143,brute,11,uniform,"{'algorithm': 'brute', 'n_neighbors': 11, 'wei...",0.933333,1.0,1.000000,0.966667,1.0,0.980000,0.026667,5
37,0.003334,0.000284,0.004264,0.000628,brute,11,distance,"{'algorithm': 'brute', 'n_neighbors': 11, 'wei...",0.966667,1.0,1.000000,0.966667,1.0,0.986667,0.016330,1
38,0.003469,0.000183,0.005222,0.000684,brute,13,uniform,"{'algorithm': 'brute', 'n_neighbors': 13, 'wei...",0.933333,1.0,0.966667,0.966667,1.0,0.973333,0.024944,22
39,0.003551,0.000597,0.003891,0.000507,brute,13,distance,"{'algorithm': 'brute', 'n_neighbors': 13, 'wei...",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,5

In [133]:
df_knn.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_algorithm', 'param_n_neighbors', 'param_weights', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'split3_test_score', 'split4_test_score', 'mean_test_score',
       'std_test_score', 'rank_test_score'],
      dtype='object')

In [134]:
results_knn= df_knn[["param_algorithm","param_n_neighbors","param_weights","mean_test_score"]].sort_values(by="mean_test_score",ascending=False)

In [135]:
results_knn.head(20)

   param_algorithm  param_n_neighbors param_weights  mean_test_score
7             auto                 11      distance         0.986667
37           brute                 11      distance         0.986667
27         kd_tree                 11      distance         0.986667
17       ball_tree                 11      distance         0.986667
9             auto                 13      distance         0.980000
3             auto                  7      distance         0.980000
6             auto                 11       uniform         0.980000
2             auto                  7       uniform         0.980000
36           brute                 11       uniform         0.980000
32           brute                  7       uniform         0.980000
34           brute                  9       uniform         0.980000
33           brute                  7      distance         0.980000
23         kd_tree                  7      distance         0.980000
19       ball_tree                 13      distance         0.980000
13       ball_tree                  7      distance         0.980000
12       ball_tree                  7       uniform         0.980000
39           brute                 13      distance         0.980000
29         kd_tree                 13      distance         0.980000
16       ball_tree                 11       uniform         0.980000
22         kd_tree                  7       uniform         0.980000

In [136]:
from sklearn.model_selection import RandomizedSearchCV
classifier_rscv_svm=RandomizedSearchCV((model_svm),{
    "C" : [1,10,20,30],
    "kernel" :["rbf","linear"]
},n_iter=4,cv=5,return_train_score=False)

In [137]:
classifier_rscv_svm.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [138]:
classifier_rscv_svm.cv_results_

{'mean_fit_time': array([0.00442953, 0.00413394, 0.00470142, 0.004144  ]),
 'std_fit_time': array([0.00032723, 0.00024095, 0.00129753, 0.00033808]),
 'mean_score_time': array([0.00332661, 0.0032896 , 0.00325494, 0.00381165]),
 'std_score_time': array([0.00013614, 0.00065605, 0.00021168, 0.00104386]),
 'param_kernel': masked_array(data=['linear', 'rbf', 'rbf', 'linear'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[1, 20, 10, 20],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'linear', 'C': 1},
  {'kernel': 'rbf', 'C': 20},
  {'kernel': 'rbf', 'C': 10},
  {'kernel': 'linear', 'C': 20}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.9       , 0.96666667, 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.96666667, 0.98      , 0.96666667]),
 'std_test_score': array([0.01632993, 0.03651484, 0.01632993, 0.0421637 ]),
 'rank_test_score': array([1, 3, 1, 4], dtype=int32)}

In [139]:
df_rscv_svm=pd.DataFrame(classifier_rscv_svm.cv_results_)

In [140]:
df_rscv_svm

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004430,0.000327,0.003327,0.000136,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.004134,0.000241,0.003290,0.000656,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
2,0.004701,0.001298,0.003255,0.000212,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.004144,0.000338,0.003812,0.001044,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,4

In [141]:
df_rscv_svm[["param_C","param_kernel","mean_test_score"]].sort_values(by="mean_test_score",ascending=False)

   param_C param_kernel  mean_test_score
0        1       linear         0.980000
2       10          rbf         0.980000
1       20          rbf         0.966667
3       20       linear         0.966667

In [142]:
# from xgboost import XGBClassifier
# df['species']=df['species'].map({'setosa':0,'versicolor':1,'virginica':2})
# y=df['species']
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

# model_xg=XGBClassifier()
# model_xg.fit(X_train,y_train)

In [143]:
# xg_predict=model_xg.predict(X_test)

In [144]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,f1_score

In [145]:
# accuracy_score(y_test,xg_predict)

In [146]:
from sklearn.ensemble import RandomForestClassifier
model_rf=RandomForestClassifier()
model_rf.fit(X_train,y_train)

RandomForestClassifier()

In [147]:
y_rf=model_rf.predict(X_test)

In [148]:
model_rf.score(X_test,y_test)

0.98

In [149]:
accuracy_score(y_test,y_rf)

0.98

In [150]:
confusion_matrix(y_test,y_rf)

array([[19,  0,  0],
       [ 0, 15,  0],
       [ 0,  1, 15]])

In [151]:
print(classification_report(y_test,y_rf))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       0.94      1.00      0.97        15
   virginica       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50

In [157]:
sepal_length = float(input("Enter sepal length: "))
sepal_width = float(input("Enter sepal width: "))
petal_length = float(input("Enter petal length: "))
petal_width = float(input("Enter petal width: "))

sample = [[
    sepal_length,
    sepal_width,
    petal_length,
    petal_width
]]


prediction = model_rf.predict(sample)

print("Predicted Species:", prediction)

Enter sepal length: 20.1
Enter sepal width: 100
Enter petal length: 10.45
Enter petal width: 0.2
Predicted Species: ['virginica']